resources:
- repo: self
phases:
- phase: OpenShift_West
  condition: succeeded()
  queue:
    name: UWHP OpenShift West
    demands: sh
  steps:
  - task: ms-devlabs.utilitytasks.task-Shellpp.Shell++@0
    displayName: Shell Script
    inputs:
      type: InlineScript
      script: 'oc start-build $(Build.Repository.Name) -w --follow=true -n openshift'
- phase: OpenShift_North
  condition: succeeded()
  dependsOn: OpenShift_West
  queue:
    name: UWHP OpenShift North
    demands: sh
  steps:
  - task: ms-devlabs.utilitytasks.task-Shellpp.Shell++@0
    displayName: Shell Script
    inputs:
      type: InlineScript
      script: 'oc start-build $(Build.Repository.Name) -w --follow=true -n openshift'
