apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: descheduler
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      name: descheduler
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: "true"
    spec:
      template:
        spec:
          serviceAccountName: descheduler
          containers:
          - name: descheduler
            image: 172.30.1.1:5000/openshift/descheduler:latest
            volumeMounts:
            - mountPath: /policy-dir
              name: policy-volume
            command:           
            - "/bin/sh"
            - "-c"
            - |
              /bin/descheduler --policy-config-file /policy-dir/configmap-policy.yaml
          restartPolicy: "OnFailure"
          volumes:
          - name: policy-volume
            configMap:
              name: descheduler