apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: descheduler
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      name: descheduler
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: "true"
    spec:
      template:
        spec:
          serviceAccountName: descheduler
          containers:
          - name: descheduler
            image: ${DOCKER_REGISTRY_HOST}:5000/openshift/descheduler:latest
            volumeMounts:
            - mountPath: /policy-dir
              name: policy-volume
            command:           
            - "/bin/sh"
            - "-c"
            - |
              /bin/descheduler --v=4 --policy-config-file /policy-dir/configmap-policy.yaml
          restartPolicy: "OnFailure"
          volumes:
          - name: policy-volume
            configMap:
              name: descheduler
parameters:
- description: docker registry host name
  displayName: Site domain
  name: DOCKER_REGISTRY_HOST
  required: true
  value: docker-registry.default.svc